# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [master]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email "subigya.lamichhane@harness.io".
      - run: git config --global user.name "Subigya Lamichhane"
      - run: npm run bump
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: 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
